vhost: fix clippy warnings on Rust 1.85
Our CI is being upgraded to Rust 1.85 and this will produce new warnings
from clippy like this one:

  error: this `map_or` can be simplified
    --> vhost/src/vhost_kern/mod.rs:79:12
     |
  79 |           if GuestAddress(config_data.desc_table_addr)
     |  ____________^
  80 | |             .checked_add(desc_table_size)
  81 | |             .map_or(true, |v| !m.address_in_range(v))
     | |_____________________________________________________^
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
     = note: `-D clippy::unnecessary-map-or` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(clippy::unnecessary_map_or)]`
  help: use is_none_or instead
     |
  79 ~         if GuestAddress(config_data.desc_table_addr)
  80 +             .checked_add(desc_table_size).is_none_or(|v| !m.address_in_range(v))
     |

Apply the advice using `cargo clippy --fix`.

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>