vhost: fix clippy deprecating `feature = "cargo-clippy"`
The latest toolchain update in rust-vmm-ci caused the following
error:

  error: unexpected `cfg` condition value: `cargo-clippy`
     --> vhost/src/vhost_user/message.rs:758:16
      |
  758 |     #[cfg_attr(feature = "cargo-clippy", allow(clippy::useless_conversion))]
      |                ^^^^^^^^^^^^^^^^^^^^^^^^
      |

As suggested in [1], today is no longer needed to check the
`cargo-clippy` feature (which has been deprecated), but we can
just use `#[allow(clippy::lint_name)]`.

[1] https://blog.rust-lang.org/2024/02/28/Clippy-deprecating-feature-cargo-clippy.html

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>