vhost: fix clippy `doc list item missing indentation`
The new clippy in rust-vmm-ci complain about this:

error: doc list item missing indentation
   --> vhost/src/vhost_user/connection.rs:305:9
    |
305 |     /// In other words, recvmsg() operations must not cross the packet boundary, other...
    |         ^
    |
    = help: if this is supposed to be its own paragraph, add a blank line
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
    = note: `-D clippy::doc-lazy-continuation` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::doc_lazy_continuation)]`

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>